# Generated by Django 4.2.8 on 2023-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetogory',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_adi',
            field=models.CharField(max_length=200),
        ),
    ]
